server:
  port: 8080

spring:
  application:
    name: enum-convert
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gurenkai.com:9306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: demo
    password: demo123

mybatis-plus:
  # 配置 mapper xml 路径
  mapperLocations: classpath:mapper/**/*.xml
  # 搜索指定包别名
  typeAliasesPackage: com.gurenkai.demo.persistence
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #开启sql日志
    map-underscore-to-camel-case: true